version: '3.8'

services:
  app:
    image: techorc-app-image
    container_name: techorc-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=${DB_NAME:-techorc}
    - POSTGRES_USER=${DB_USER:-postgres}
    - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
